### ISSUE TITLE
Dask arrays have no dtype attribute 

### ISSUE THREAD

**Issue by wtbarnes** [intake/intake-astro#4]
When I create a source from multiple (local) FITS files, I'm able to construct a Dask array using `to__dask()`. However, the resulting Dask array has no `dtype` attribute. It does have a `shape` attribute.

E.g.

```python
import intake
>>> source = intake.open_fits_array('data/*.fits', ext=0)
>>> darr = source.to_dask()
>>> darr.dtype 
```

gives

```Python traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-65-2fad671c8367> in <module>
----> 1 darr.dtype

~/anaconda/envs/aia-on-pleiades/lib/python3.7/site-packages/dask/array/core.py in dtype(self)
   1042     @property
   1043     def dtype(self):
-> 1044         return self._meta.dtype
   1045 
   1046     def _get_chunks(self):

AttributeError: 'tuple' object has no attribute 'dtype'
```

Furthermore, `darr._meta` simply returns the `shape` attribute. 

I've dug a bit into how `_meta` is set in `dask.array.Array`, but cannot seem to figure out where exactly the intake loader is missing this bit of information. Any pointers would be helpful! I can also supply a few example FITS files for debugging if needed. 

If this is a bug in `intake-astro` or a feature that needs implementing, I'd be happy to open a PR to do so.

**Comment by martindurant** [comment]
The call signature for `dask.array.Array` changed recently, and hasn't been updated here yet. You could downgrade Dask, or, I think the following change would do it:
```diff
--- a/intake_astro/array.py
+++ b/intake_astro/array.py
@@ -88,7 +88,8 @@ class FITSArraySource(DataSource):
                     dask[(name,) + bits] = (
                         _get_section, self.files[0], self.ext, slices, True
                     )
-            self.arr = da.Array(dask, name, chunks, self.dtype, self.shape)
+            self.arr = da.Array(dask, name, chunks, dtype=self.dtype,
+                                shape=self.shape)
             self._schema = Schema(
                 dtype=self.dtype,
                 shape=self.shape,
```

Would you mind trying and, if it works, submitting this as a PR? Note that the change is backward compatible.

**Comment by wtbarnes** [comment]
That seems to have worked! See #5
